# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
tipoinstituciones = Tipoinstitucione.create([{ nombre:'Universidad'}, { nombre: 'Instituto Profesional'},{nombre: 'Otros'}])
tiporelacione = Tiporelacione.create([{ nombre:'Pública'}, { nombre: 'Privada con aportes estatales'},{nombre: 'Privada sin aportes estatales'}])
paise = Paise.create([{ nombre:'Chile'},{ nombre:'Colombia'}])
region = Region.create([{ nombre:'Metropolitana', paise_id:'1'},{ nombre:'Medellin', paise_id:'2'}])
cat = Cat.create([{nombre:'Datos Institucionales'},{nombre:'Gobernanza'},{nombre:'Cultura'},{nombre:'Academia'},{nombre:'Campus'},{nombre:'Responsabilidad Social'}])
subcat = Subcat.create([{nombre:'Población',cat_id:'1'},{nombre:'Instalaciones',cat_id:'1'},{nombre:'Año Base',cat_id:'1'}])
subcat = Subcat.create([{nombre:'GOB1. Participación de grupos de interés',cat_id:'2'},{nombre:'GOB2. Compromiso Institucional',cat_id:'2'},{nombre:'GOB3. Plan/Estrategia de Sustentabilidad',cat_id:'2'},{nombre:'GOB4. Reportabilidad y Transparencia',cat_id:'2'},{nombre:'GOB5. Huella de Carbono',cat_id:'2'},{nombre:'GOB6. Coordinación Sustentabilidad',cat_id:'2'}])
subcat = Subcat.create([{nombre:'CU1. Estudiantes promotores de la Sustentabilidad',cat_id:'3'},{nombre:'CU2. Inducción a la Sustentabilidad para estudiantes',cat_id:'3'},{nombre:'CU3. Funcionarios promotores de la Sustentabilidad',cat_id:'3'},{nombre:'CU4.Inducción a la sustentabilidad para funcionarios',cat_id:'3'},{nombre:'CU5. Programa de prácticas sustentables para oficinas',cat_id:'3'},{nombre:'CU6. Programa de desarrollo profesional en sustentabilidad',cat_id:'3'},
{nombre:'CU7. Actividades de difusión y sensibilización',cat_id:'3'}])
subcat = Subcat.create([{nombre:'AC1. Curso mínimo transversal de pregrado',cat_id:'4'},{nombre:'AC2. Capacitación profesores',cat_id:'4'},{nombre:'AC3. Evaluación conocimiento sustentabilidad de estudiantes',cat_id:'4'},{nombre:'AC4. Programas de postgrado que incluyen competencias en sustentabilidad',cat_id:'4'},{nombre:'AC5. Programas de pregrado que incluyen competencias en sustentabilidad',cat_id:'4'},{nombre:'AC6. Apoyo a la investigación en sustentabilidad',cat_id:'4'}])
subcat = Subcat.create([{nombre:'AC7. Investigación enfocada en sustentabilidad',cat_id:'4'},{nombre:'AC8. Transferencia de conocimiento',cat_id:'4'}])
subcat = Subcat.create([{nombre:'GC1. Huella Hidríca',cat_id:'5'},{nombre:'GC2. Reducción del consumo de agua',cat_id:'5'},{nombre:'GC3. Biodiversidad',cat_id:'5'},{nombre:'GC4. Manejo sustentable de jardines',cat_id:'5'},{nombre:'GC5. Alimentación',cat_id:'5'},{nombre:'GC6. Programa de compras sustentables',cat_id:'5'},
{nombre:'GC7. Diseño y construcción',cat_id:'5'},{nombre:'GC8. Operación y mantención',cat_id:'5'},{nombre:'GC9. Consumo de energía',cat_id:'5'},{nombre:'GC10. Energía renovable',cat_id:'5'},{nombre:'GC11. Generación de residuos',cat_id:'5'},{nombre:'GC12. Recuperación de residuos',cat_id:'5'},{nombre:'GC13. Residuos peligrosos',cat_id:'5'},
{nombre:'GC14. Participación modal medios de transporte',cat_id:'5'},{nombre:'GC15. Plan transporte sustentable',cat_id:'5'}])
subcat = Subcat.create([{nombre:'RS1. Asequibilidad',cat_id:'6'},{nombre:'RS2. Política de inclusión',cat_id:'6'},{nombre:'RS3. Equidad de género',cat_id:'6'},{nombre:'RS4. Colaboración',cat_id:'6'},{nombre:'RS5. PArticipación en políticas públicas',cat_id:'6'},{nombre:'RS6. Comunidades vecinas',cat_id:'6'},
{nombre:'RS7. Compensación del personal',cat_id:'6'},{nombre:'RS8. Satisfacción laboral',cat_id:'6'},{nombre:'RS9. Sindicalización',cat_id:'6'}])

user=User.create([{email:'johanna.munozi@utem.cl',password:'123456',rol:'admin'}])

question = Question.create([{indicador: 'DI12', pregunta: 'Número total de estudiantes de pregrado' , tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '1'}])
question = Question.create([{indicador: 'DI13', pregunta: 'Número total de estudiantes de postgrado', tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '1'}])
question = Question.create([{indicador: 'DI14', pregunta: 'Número total de estudiantes de pregrado admitidos en el año de evaluación' , tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '1'}])
question = Question.create([{indicador: 'DI15', pregunta: 'Número total de estudiantes de postgrado admitidos en el año de evaluación', tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '1'}])
question = Question.create([{indicador: 'DI16', pregunta: 'Número total de estudiantes de pregrado egresados durante el año de evaluación', tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '1'}])
question = Question.create([{indicador: 'DI17', pregunta: 'Número total de estudiantes de postgrado egresados durante el año de evaluación', tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '1'}])
question = Question.create([{indicador: 'DI18', pregunta: 'Total de jornadas equivalentes de académicos', tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '1'}])
question = Question.create([{indicador: 'DI19', pregunta: 'Número total de académicos titulares', tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '1'}])
question = Question.create([{indicador: 'DI20', pregunta: 'Total de jornadas equivalentes de trabajadores no académicos', tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '1'}])
question = Question.create([{indicador: 'DI21', pregunta: 'Número total de trabajadores en cargos directivos (hasta 3ª nivel de jerarquía)', tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '1'}])

question = Question.create([{indicador: 'DI22', pregunta: 'Describa las instalaciones de la institución, incluyendo información sobre sus campus, que son consideradas en esta evaluación. Explique y justifique por que se han dejado fuera algunas instalaciones.', tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '2'}])
question = Question.create([{indicador: 'DI23', pregunta: 'Superficie total de terreno propiedad (o en arriendo) de la institución (Hectáreas).', tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '2'}])
question = Question.create([{indicador: 'DI24', pregunta: 'Superficie total designada como áreas verdes (Hectáreas)', tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '2'}])
question = Question.create([{indicador: 'DI25', pregunta: 'Superficie total construida (Metros cuadrados)', tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '2'}])
question = Question.create([{indicador: 'DI26', pregunta: 'Superficie total de edificios recepcionada (entregada para iniciar su uso) en los últimos cinco años (Metros cuadrados)', tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '2'}])

question = Question.create([{indicador: 'DI27', pregunta: 'Año base emisiones de gases de efecto invernadero', tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '3'}])
question = Question.create([{indicador: 'DI28', pregunta: 'Emisión de gases de efecto invernadero Alcance 1 y 2  para año base  (Ton CO2-e)', tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '3'}])
question = Question.create([{indicador: 'DI29', pregunta: 'Emisión de gases de efecto invernadero Alcance 1, 2 y 3 para año base (Ton CO2-e)', tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '3'}])
question = Question.create([{indicador: 'DI30', pregunta: 'Año base consumo de energía' , tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '3'}])
question = Question.create([{indicador: 'DI31', pregunta: 'Consumo de energía por metro cuadrado construido para año base (MWh/metro cuadrado construido)', tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '3'}])
question = Question.create([{indicador: 'DI32', pregunta: 'Año base consumo de agua', tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '3'}])
question = Question.create([{indicador: 'DI33', pregunta: 'Consumo de agua por persona  para año base (Metros cúbicos /persona)', tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '3'}])
question = Question.create([{indicador: 'DI34', pregunta: 'Año base generación de residuos', tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '3'}])
question = Question.create([{indicador: 'DI35', pregunta: 'Generación residuos no recuperados por persona para año base (Toneladas/persona)', tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '3'}])

question = Question.create([{indicador: 'GOB1.1',pregunta:'Existen instancias de representatividad para el conjunto de estudiantes elegidas de forma democrática. Estas deben representar a la totalidad de los estudiantes de la institución.',subcat_id:'4',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'12.5',question_id:'25'},{nombre:'No',puntaje:'0.0',question_id:'25'}])
question = Question.create([{indicador: 'GOB1.2',pregunta:'Existen instancias de representatividad de trabajadores elegidas de forma democrática.',subcat_id:'4',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'12.5',question_id:'26'},{nombre:'No',puntaje:'0.0',question_id:'26'}])
question = Question.create([{indicador: 'GOB1.3',pregunta:'Existen instancias de representatividad de académicos elegidas de forma democrática. ',subcat_id:'4',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'12.5',question_id:'27'},{nombre:'No',puntaje:'0.0',question_id:'27'}])
question = Question.create([{indicador: 'GOB1.4',pregunta:'Existen instancias formales de diálogo con representantes de las comunidades aledañas a los territorios donde están insertas las instalaciones de la institución.',subcat_id:'4',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'12.5',question_id:'28'},{nombre:'No',puntaje:'0.0',question_id:'28'}])
question = Question.create([{indicador: 'GOB1.5',pregunta:'La máxima instancia de gobierno institucional cuenta con un representante de los estudiantes.',subcat_id:'4',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'12.5',question_id:'29'},{nombre:'No',puntaje:'0.0',question_id:'29'}])
question = Question.create([{indicador: 'GOB1.6',pregunta:'La máxima instancia de gobierno institucional cuenta con un representante de los trabajadores.',subcat_id:'4',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'12.5',question_id:'30'},{nombre:'No',puntaje:'0.0',question_id:'30'}])
question = Question.create([{indicador: 'GOB1.7',pregunta:'La máxima instancia de gobierno institucional cuenta con un representante de los académicos.',subcat_id:'4',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'12.5',question_id:'31'},{nombre:'No',puntaje:'0.0',question_id:'31'}])
question = Question.create([{indicador: 'GOB1.8',pregunta:'La máxima instancia de gobierno institucional cuenta con un representante de los comunidad local.',subcat_id:'4',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'12.5',question_id:'32'},{nombre:'No',puntaje:'0.0',question_id:'32'}])

question = Question.create([{indicador: 'GOB2.1',pregunta:'Existe un compromiso explícito con la sustentabilidad en el plan/estrategia institucional.',subcat_id:'5',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'23.O',question_id:'33'},{nombre:'No',puntaje:'0.0',question_id:'33'}])
question = Question.create([{indicador: 'GOB2.2',pregunta:'Cuenta con una política de sustentabilidad.',subcat_id:'5',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'11.0',question_id:'34'},{nombre:'No',puntaje:'0.0',question_id:'34'}])
question = Question.create([{indicador: 'GOB2.3',pregunta:'La política Incluye una definición de sustentabilidad que considera todas sus dimensiones.',subcat_id:'5',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'11.0',question_id:'35'},{nombre:'No',puntaje:'0.0',question_id:'35'}])
question = Question.create([{indicador: 'GOB2.4',pregunta:'La política incluye un compromiso de promover la sustentabilidad en la sociedad.',subcat_id:'5',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'11.0',question_id:'36'},{nombre:'No',puntaje:'0.0',question_id:'36'}])
question = Question.create([{indicador: 'GOB2.5',pregunta:'La política incluye un compromiso de promover la sustentabilidad en la investigación.',subcat_id:'5',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'11.0',question_id:'37'},{nombre:'No',puntaje:'0.0',question_id:'37'}])
question = Question.create([{indicador: 'GOB2.6',pregunta:'La política incluye un compromiso de promover la sustentabilidad en la la formación de estudiantes,',subcat_id:'5',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'11.0',question_id:'38'},{nombre:'No',puntaje:'0.0',question_id:'38'}])
question = Question.create([{indicador: 'GOB2.7',pregunta:'La política incluye un compromiso a promover la sustentabilidad en las gestión de sus instalaciones.',subcat_id:'5',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'11.0',question_id:'39'},{nombre:'No',puntaje:'0.0',question_id:'39'}])
question = Question.create([{indicador: 'GOB2.8',pregunta:'La política establece el compromiso de crear un plan o estrategia de sustentabilidad. ',subcat_id:'5',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'11.0',question_id:'40'},{nombre:'No',puntaje:'0.0',question_id:'40'}])

question = Question.create([{indicador: 'GOB3.1',pregunta:'Cuenta con un plan o estrategia de sustentabilidad.',subcat_id:'6',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'1.0',question_id:'41'},{nombre:'No',puntaje:'0.0',question_id:'41'}])
question = Question.create([{indicador: 'GOB3.2',pregunta:'El plan de sustentabilidad incluye el tema mitigación de huella de carbono',subcat_id:'6',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'42'},{nombre:'No',puntaje:'0.0',question_id:'42'}])
question = Question.create([{indicador: 'GOB3.3',pregunta:'El plan de sustentabilidad incluye el tema de formación en sustentabilidad.',subcat_id:'6',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'43'},{nombre:'No',puntaje:'0.0',question_id:'43'}])
question = Question.create([{indicador: 'GOB3.4',pregunta:'El plan de sustentabilidad incluye el tema de investigación en sustentabilidad.',subcat_id:'6',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'44'},{nombre:'No',puntaje:'0.0',question_id:'44'}])
question = Question.create([{indicador: 'GOB3.5',pregunta:'El plan de sustentabilidad incluye el tema de cultura sustentable.',subcat_id:'6',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'45'},{nombre:'No',puntaje:'0.0',question_id:'45'}])
question = Question.create([{indicador: 'GOB3.6',pregunta:'El plan de sustentabilidad incluye el tema de trabajo justo.',subcat_id:'6',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'46'},{nombre:'No',puntaje:'0.0',question_id:'46'}])
question = Question.create([{indicador: 'GOB3.7',pregunta:'El plan de sustentabilidad incluye el tema de diversidad e inclusión.',subcat_id:'6',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'47'},{nombre:'No',puntaje:'0.0',question_id:'47'}])
question = Question.create([{indicador: 'GOB3.8',pregunta:'El plan de sustentabilidad incluye el tema de construcción sustentable.',subcat_id:'6',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'48'},{nombre:'No',puntaje:'0.0',question_id:'48'}])
question = Question.create([{indicador: 'GOB3.9',pregunta:'El plan de sustentabilidad incluye el tema de energía.',subcat_id:'6',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'49'},{nombre:'No',puntaje:'0.0',question_id:'49'}])
question = Question.create([{indicador: 'GOB3.10',pregunta:'El plan de sustentabilidad incluye el tema de alimentación.',subcat_id:'6',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'50'},{nombre:'No',puntaje:'0.0',question_id:'50'}])
question = Question.create([{indicador: 'GOB3.11',pregunta:'El plan de sustentabilidad incluye el tema de biodiversidad y áreas verdes.',subcat_id:'6',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'51'},{nombre:'No',puntaje:'0.0',question_id:'51'}])
question = Question.create([{indicador: 'GOB3.12',pregunta:'El plan de sustentabilidad incluye el tema de compras.',subcat_id:'6',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'52'},{nombre:'No',puntaje:'0.0',question_id:'52'}])
question = Question.create([{indicador: 'GOB3.13',pregunta:'El plan de sustentabilidad incluye el tema de transporte.',subcat_id:'6',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'53'},{nombre:'No',puntaje:'0.0',question_id:'53'}])
question = Question.create([{indicador: 'GOB3.14',pregunta:'El plan de sustentabilidad incluye el tema de residuos.',subcat_id:'6',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'54'},{nombre:'No',puntaje:'0.0',question_id:'54'}])
question = Question.create([{indicador: 'GOB3.15',pregunta:'El plan de sustentabilidad incluye el tema de agua.',subcat_id:'6',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'55'},{nombre:'No',puntaje:'0.0',question_id:'55'}])

question = Question.create([{indicador: 'GOB4.1',pregunta:'Ha desarrollado un reporte de sustentabilidad en los últimos dos años bajo metodología GRI. (Solo considerar reportes que han sido completados y lanzados)',subcat_id:'7',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'25.0',question_id:'56'},{nombre:'No',puntaje:'0.0',question_id:'56'}])
question = Question.create([{indicador: 'GOB4.2',pregunta:'El reporte ha sido verificado por una entidad externa verificada por GRI.',subcat_id:'7',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'5.0',question_id:'57'},{nombre:'No',puntaje:'0.0',question_id:'57'}])
question = Question.create([{indicador: 'GOB4.3',pregunta:'El desarrollo del reporte contempló la participación efectiva de representantes de todos los estamentos.',subcat_id:'7',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'58'},{nombre:'No',puntaje:'0.0',question_id:'58'}])
question = Question.create([{indicador: 'GOB4.4',pregunta:'La institución es o ha sido parte de un acuerdo o certificación voluntaria de mejora en sustentabilidad.',subcat_id:'7',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'25.0',question_id:'59'},{nombre:'No',puntaje:'0.0',question_id:'59'}])
question = Question.create([{indicador: 'GOB4.5',pregunta:'La institución cuenta con un certificado de cumplimiento del acuerdo o certificación voluntaria.',subcat_id:'7',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'25.0',question_id:'60'},{nombre:'No',puntaje:'0.0',question_id:'60'}])

question = Question.create([{indicador: 'GOB5.1',pregunta:'Cuenta con inventarios de emisiones desarrollados de forma anual que incluyen:',subcat_id:'8',tiporespuesta:'Alternativa'}])
alternativa = Alternativa.create([{nombre:'Sin inventario',puntaje:'1.0',question_id:'61'},{nombre:'Alcances 1 y 2',puntaje:'2.0',question_id:'61'},{nombre:'Alcances 1, 2 y 3',puntaje:'3.0',question_id:'61'}])
question = Question.create([{indicador: 'GOB5.2',pregunta:'El inventario de emisiones cuenta con una verificación externa.',subcat_id:'8',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'5.0',question_id:'62'},{nombre:'No',puntaje:'0.0',question_id:'62'}])
question = Question.create([{indicador: 'GOB5.3',pregunta:'Incluye las emisiones de transporte en el alcance 3.',subcat_id:'8',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'1.0',question_id:'63'},{nombre:'No',puntaje:'0.0',question_id:'63'}])
question = Question.create([{indicador: 'GOB5.4',pregunta:'Incluye las emisiones de residuos en el alcance 3.',subcat_id:'8',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'1.0',question_id:'64'},{nombre:'No',puntaje:'0.0',question_id:'64'}])
question = Question.create([{indicador: 'GOB5.5',pregunta:'Incluye las emisiones de compras de insumos clave en el alcance 3.',subcat_id:'8',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'1.0',question_id:'65'},{nombre:'No',puntaje:'0.0',question_id:'65'}])
question = Question.create([{indicador: 'GOB5.6',pregunta:'Incluye las emisiones de otros flujos en el alcance 3.',subcat_id:'8',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'1.0',question_id:'66'},{nombre:'No',puntaje:'0.0',question_id:'66'}])
question = Question.create([{indicador: 'GOB5.7',pregunta:'Ha establecido un compromiso formal de neutralidad de carbono, considerando:',subcat_id:'8',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Alcances 1 y 2',puntaje:'10.0',question_id:'67'},{nombre:'Alcances 1, 2 y 3',puntaje:'15.0',question_id:'67'},{nombre:'Sin compromiso',puntaje:'0.0',question_id:'67'}])
question = Question.create([{indicador: 'GOB5.8',pregunta:'Emisiones totales para año evaluado (Ton CO2-e) (Año ingresado en datos institucionales, indicador DI11)',subcat_id:'8',tiporespuesta:'Ingresa Valor Manualmente'}])

question = Question.create([{indicador: 'GOB6.1',pregunta:'Existe una entidad dedicada a ejecutar la iniciativa de sustentabilidad  de forma transversal, la cuál esta mejor descrita por:',subcat_id:'9',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Un profesional a cargo',puntaje:'20.0',question_id:'69'},{nombre:'Un equipo dedicado',puntaje:'50.0',question_id:'69'},{nombre:'Una dirección que coordina varias unidades dedicadas',puntaje:'70',question_id:'69'}])
question = Question.create([{indicador: 'GOB6.2',pregunta:'Existe un comité con representantes de distintos estamentos de la institución que apoya la labor de la entidad',subcat_id:'9',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'30.0',question_id:'70'},{nombre:'No',puntaje:'0.0',question_id:'70'}])

question = Question.create([{indicador: 'CU1.1',pregunta:'Existen iniciativas, dirigidas a estudiantes, para la formación de promotores de la sustentabilidad',subcat_id:'10',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'1.0',question_id:'71'},{nombre:'No',puntaje:'0.0',question_id:'71'}])
question = Question.create([{indicador: 'CU1.2',pregunta:'La iniciativa esta dirigida a quiénes asumirán la tarea de formar a pares y/o liderar procesos de cambios entre sus pares.',subcat_id:'10',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'1.0',question_id:'72'},{nombre:'No',puntaje:'0.0',question_id:'72'}])
question = Question.create([{indicador: 'CU1.3',pregunta:'La iniciativa esta enlazada con oportunidades de trabajo (voluntario o remunerado) para los participantes, donde puedan poner en práctica su aprendizaje.',subcat_id:'10',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'1.0',question_id:'73'},{nombre:'No',puntaje:'0.0',question_id:'73'}])
question = Question.create([{indicador: 'CU1.4',pregunta:'Se otorga un reconocimiento formal por la participación en el programa que incluye objetivos y horas dedicadas.',subcat_id:'10',tiporespuesta:'Si - No'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'1.0',question_id:'74'},{nombre:'No',puntaje:'0.0',question_id:'74'}])
question = Question.create([{indicador: 'CU1.5',pregunta:'Número de estudiantes que han participado de la iniciativa en los últimos 5 años',subcat_id:'10',tiporespuesta:'Ingresa Valor Manualmente'}])


question = Question.create([{indicador: 'CU2.1', pregunta:'Existe un programa de inducción de sustentabilidad dirigido a estudiantes de pre y postgrado donde se da a conocer  los siguientes temas:
- Política de sustentabilidad: Dar a conocer el compromiso institucional con la sustentabilidad
- Gestión de campus: Información sobre diversas iniciativas asociadas a las operaciones y servicios de las instalaciones de la institución (Ej: residuos, transporte, energía, alimentación)
- Formación: Oportunidades de formación en sustentabilidad disponibles
- Participación: Oportunidades de participación en iniciativas de sustentabilidad.', tiporespuesta: 'Si - No', subcat_id: '11'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'1.0',question_id:'76'},{nombre:'No',puntaje:'0.0',question_id:'76'}])
question = Question.create([{indicador: 'CU2.2', pregunta: 'Número de estudiantes de pre y postgrado admitidos durante el periódo de evaluación que han participado en al menos una actividad de inducción en temas de sustentabilidad', tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '11'}])


question = Question.create([{indicador: 'CU3.1', pregunta: 'Existen iniciativas, dirigidas a funcionarios, para la formación de promotores de la sustentabilidad' , tiporespuesta: 'Si - No', subcat_id: '12'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'1.0',question_id:'78'},{nombre:'No',puntaje:'0.0',question_id:'78'}])
question = Question.create([{indicador: 'CU3.2', pregunta: 'La iniciativa esta dirigida a quiénes asumirán la tarea de formar a pares y/o liderar procesos de cambios entre sus pares.' , tiporespuesta: 'Si - No', subcat_id: '12'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'1.0',question_id:'79'},{nombre:'No',puntaje:'0.0',question_id:'79'}])
question = Question.create([{indicador: 'CU3.3', pregunta: 'La iniciativa esta enlazada con oportunidades de trabajo (voluntario o remunerado) para los participantes, donde puedan poner en práctica su aprendizaje.' , tiporespuesta: 'Si - No', subcat_id: '12'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'1.0',question_id:'80'},{nombre:'No',puntaje:'0.0',question_id:'80'}])
question = Question.create([{indicador: 'CU3.4', pregunta: 'Se otorga un reconocimiento formal por la participación en el programa que incluye objetivos y horas dedicadas.', tiporespuesta: 'Si - No', subcat_id: '12'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'1.0',question_id:'81'},{nombre:'No',puntaje:'0.0',question_id:'81'}])
question = Question.create([{indicador: 'CU3.5', pregunta: 'Número de trabajadores que han participado de las iniciativas en los últimos 5 años' , tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '12'}])


question = Question.create([{indicador: 'CU4.1', pregunta: 'Existe un programa de inducción de sustentabilidad  para trabajadores (no académicos) donde se da a conocer los siguientes temas:
- Política de sustentabilidad: Dar a conocer el compromiso institucional con la sustentabilidad
- Gestión de campus: Información sobre diversas iniciativas asociadas a las operaciones y servicios de las instalaciones de la institución (Ej: residuos, transporte, energía, alimentación)
- Formación: Oportunidades de formación en sustentabilidad disponibles
- Participación: Oportunidades de participación en iniciativas de sustentabilidad.', tiporespuesta: 'Si - No', subcat_id: '13'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'1.0',question_id:'83'},{nombre:'No',puntaje:'0.0',question_id:'83'}])
question = Question.create([{indicador: 'CU4.2', pregunta: 'Número de trabajadores que han participado en al menos una actividad de inducción en temas de sustentabilidad en los últimos 3 años', tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '13'}])


question = Question.create([{indicador: 'CU5.1', pregunta: 'Existe un programa de buenas prácticas sustentables que incluya al menos las siguientes carácterísticas:
- Cuenta con una herramienta de autoevaluación, simple y didáctica, que oriente las acciones en la oficina.
- Cuenta con mecanismos de reconocimiento anual para las oficinas destacadas.
- Cuenta con instancias de capacitación para quiénes lleven adelante el programa.
- Mantiene un catástro de las oficinas existentes en la institución y aquellas activamente participando en el programa.' , tiporespuesta: 'Si - No', subcat_id: '14'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'1.0',question_id:'85'},{nombre:'No',puntaje:'0.0',question_id:'85'}])
question = Question.create([{indicador: 'CU5.2', pregunta: 'Número de oficinas afiliadas y activas en el programa' , tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '14'}])
question = Question.create([{indicador: 'CU5.3', pregunta: 'Número total de oficinas en la intitución', tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '14'}])


question = Question.create([{indicador: 'CU6.1', pregunta: 'La institución tiene disponible alternativas de capacitación para sus trabajadores en temas de sustentabilidad', tiporespuesta: 'Si - No', subcat_id: '15'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'1.0',question_id:'88'},{nombre:'No',puntaje:'0.0',question_id:'88'}])
question = Question.create([{indicador: 'CU6.2', pregunta: 'Número de trabajadores de la institución que ha participado del programa el último año', tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '15'}])


question = Question.create([{indicador: 'CU7.1', pregunta: 'Ha realizado al menos una feria con la participación de distintas iniciativas de sustentabilidad en el último año', tiporespuesta:'Si - No', subcat_id: '16'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'90'},{nombre:'No',puntaje:'0.0',question_id:'90'}])
question = Question.create([{indicador: 'CU7.2', pregunta: 'Ha realizado al menos una feria con la participación de distintas iniciativas de sustentabilidad en el último año' , tiporespuesta: 'Si - No', subcat_id: '16'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'91'},{nombre:'No',puntaje:'0.0',question_id:'91'}])
question = Question.create([{indicador: 'CU7.3', pregunta: 'Cuenta con un grupo activo de estudiantes dedicados a promover la sustentabilidad' , tiporespuesta: 'Si - No', subcat_id: '16'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'92'},{nombre:'No',puntaje:'0.0',question_id:'92'}])
question = Question.create([{indicador: 'CU7.4', pregunta: 'Cuenta con un portal web dedicado a difundir la iniciativa de sustentabilidad de la institución' , tiporespuesta: 'Si - No', subcat_id: '16'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'93'},{nombre:'No',puntaje:'0.0',question_id:'93'}])
question = Question.create([{indicador: 'CU7.5', pregunta: 'Hay un enlace directo al portal de sustentabilidad en la página principal de la institución.' , tiporespuesta: 'Si - No', subcat_id: '16'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'94'},{nombre:'No',puntaje:'0.0',question_id:'94'}])
question = Question.create([{indicador: 'CU7.6', pregunta: 'La unidad envía al menos un correo a todos sus estudiante al año, dedicado a la difusión de la sustentabilidad', tiporespuesta: 'Si - No', subcat_id: '16'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'95'},{nombre:'No',puntaje:'0.0',question_id:'95'}])
question = Question.create([{indicador: 'CU7.7', pregunta: 'Ha sostenido al menos una serie de charlas con expertos dedicadas a la sustentabilidad, abiertas a todos sus estudiantes.', tiporespuesta: 'Si - No', subcat_id: '16'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'96'},{nombre:'No',puntaje:'0.0',question_id:'96'}])
question = Question.create([{indicador: 'CU7.8', pregunta: 'Otras actividades cocurriculares o esfuerzos de difusión que no corresponde a las previamente descritas', tiporespuesta: 'Si - No', subcat_id: '16'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'97'},{nombre:'No',puntaje:'0.0',question_id:'97'}])


question = Question.create([{indicador: 'AC1.1', pregunta: 'Se imparte al menos un curso optativo introductorio de sustentabilidad, abierto a todos los estudiantes. ', tiporespuesta: 'Si - No', subcat_id: '17'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'5.0',question_id:'98'},{nombre:'No',puntaje:'0.0',question_id:'98'}])
question = Question.create([{indicador: 'AC1.2', pregunta: 'Se imparten cursos introductorios de sustentabilidad a los estudiantes de caracter obligatorio', tiporespuesta: 'Si - No', subcat_id: '17'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'1.0',question_id:'99'},{nombre:'No',puntaje:'0.0',question_id:'99'}])
question = Question.create([{indicador: 'AC1.3', pregunta: 'Número de alumnos admitidos durante el año de evaluación en programas/carreras que cuenten con al menos un curso obligatorio de introducción a la sustentabilidad.', tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '17'}])


question = Question.create([{indicador: 'AC2.1', pregunta: 'Existe un programa de programa de capacitación en docencia de la sustentabilidad dirigido a los académicos de la institución.', tiporespuesta: 'Si - No', subcat_id: '18'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'1.0',question_id:'101'},{nombre:'No',puntaje:'0.0',question_id:'101'}])
question = Question.create([{indicador: 'AC2.2', pregunta: 'El programa incluye el tema: competencias en sustentabilidad del egresado.', tiporespuesta: 'Si - No', subcat_id: '18'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'1.0',question_id:'102'},{nombre:'No',puntaje:'0.0',question_id:'102'}])
question = Question.create([{indicador: 'AC2.3', pregunta: 'El programa incluye el tema: conocimientos de ecosistemas, ciclos naturales, impacto ambiental.', tiporespuesta: 'Si - No', subcat_id: '18'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'1.0',question_id:'103'},{nombre:'No',puntaje:'0.0',question_id:'103'}])
question = Question.create([{indicador: 'AC2.4', pregunta: 'El programa incluye el tema: los desafíos que enfrenta la sociedad tanto local como globalmente y el potencial rol de los educadores y estudiantes.', tiporespuesta: 'Si - No', subcat_id: '18'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'1.0',question_id:'104'},{nombre:'No',puntaje:'0.0',question_id:'104'}])
question = Question.create([{indicador: 'AC2.5', pregunta: 'El programa incluye el tema: desarrollo de habilidades prácticas y capacidad de acción en relación a la educación para el desarrollo sustentable (metodologías activas, entre otras).', tiporespuesta: 'Si - No', subcat_id: '18'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'1.0',question_id:'105'},{nombre:'No',puntaje:'0.0',question_id:'105'}])
question = Question.create([{indicador: 'AC2.6', pregunta: 'El programa incluye el tema: desarrollo de sus atributos personales y capacidades para actuar con creciente autonomía, juicio y responsabilidad personal en relación al desarrollo sustentable.', tiporespuesta: 'Si - No', subcat_id: '18'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'1.0',question_id:'106'},{nombre:'No',puntaje:'0.0',question_id:'106'}])
question = Question.create([{indicador: 'AC2.7', pregunta: 'El programa considera otorgar un reconocimiento formal por la participación en el programa, que incluya objetivos y horas dedicadas.', tiporespuesta: 'Si - No', subcat_id: '18'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'1.0',question_id:'107'},{nombre:'No',puntaje:'0.0',question_id:'107'}])
question = Question.create([{indicador: 'AC2.8', pregunta: 'Número de académicos que han participado del programa de capacitación en los últimos 5 años.', tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '18'}])


question = Question.create([{indicador: 'AC3.1', pregunta: 'Número de alumnos de pregrado admitidos durante el año de evaluación que han sido evaluados en conocimientos de sustentabilidad. La evaluación debe ser aplicable a cualquier disciplina e independiente de cursos específicos.' , tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '19'}])
question = Question.create([{indicador: 'AC3.2', pregunta: 'Número de alumnos de pregrado egresados durante el año de evaluación que han sido evaluados en conocimientos de sustentabilidad', tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '19'}])


question = Question.create([{indicador: 'AC4.1', pregunta: 'Número de alumnos egresados, durante el año evaluado, de programas de postgrado que incluyen la sustentabilidad en sus logros de aprendizaje u competencias de perfil de egreso.', tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '20'}])


question = Question.create([{indicador: 'AC5.1', pregunta: 'Número de alumnos egresados, en periodo reportado, de programas/carreras de pregrado que incluyen la sustentabilidad en sus logros de aprendizaje u competencias de perfil de egreso', tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '21'}])


question = Question.create([{indicador: 'AC6.1', pregunta: 'Existe un programa que incentiva a académicos de diversas disciplinas a desarrollar investigación enfocada en sustentabilidad. (El programa incluye alguno de los siguientes atributos, sin limitarse a ellos: financiamiento, mentoría, guías, capacitación)', tiporespuesta: 'Si - No', subcat_id: '22'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'80.0',question_id:'113'},{nombre:'No',puntaje:'0.0',question_id:'113'}])
question = Question.create([{indicador: 'AC6.2', pregunta: 'Existe un programa que incentiva a estudiantes de diversas disciplinas a desarrollar investigación enfocada en sustentabilidad. (El programa incluye alguno de los siguientes atributos, sin limitarse a ellos: financiamiento, mentoría, guías, capacitación)', tiporespuesta: 'Si - No', subcat_id: '22'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'114'},{nombre:'No',puntaje:'0.0',question_id:'114'}])


question = Question.create([{indicador: 'AC7.1', pregunta: 'Existe un listado público de investigaciones enfocadas en sustentabilidad. (El listado debe incluir el título, nombres de autores, departamento al que pertenenen, descripción de la investigación y palabras clave)', tiporespuesta:'Si - No' , subcat_id: '23'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'115'},{nombre:'No',puntaje:'0.0',question_id:'115'}])
question = Question.create([{indicador: 'AC7.2', pregunta: 'Número de investigaciones enfocadas en sustentabilidad publicadas durante el año de evaluación', tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '23'}])
question = Question.create([{indicador: 'AC7.3', pregunta: 'Número total de investigaciones publicadas durante el año de evaluación' , tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '23'}])


question = Question.create([{indicador: 'AC8.1', pregunta: 'Existen programas de difusión científica y/o  transferencia tecnológica donde se entregue financiamiento para proyectos enfocados en sustentabilidad' , tiporespuesta: 'Si - No', subcat_id: '24'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'118'},{nombre:'No',puntaje:'0.0',question_id:'118'}])
question = Question.create([{indicador: 'AC8.2', pregunta: 'Existen programas de difusión científica y/o  transferencia tecnológica donde se realicen trabajos con comunidades locales (vecinas a instalaciones de la institución), enfocados en sustentabilidad.', tiporespuesta: 'Si - No', subcat_id: '24'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'119'},{nombre:'No',puntaje:'0.0',question_id:'119'}])
question = Question.create([{indicador: 'AC8.3', pregunta: 'Existen programas de difusión científica y/o  transferencia tecnológica donde se elabore material educativo en distintos formatos, dirigido a comunidad externa, enfocado en sustentabilidad. El material debe estar disponible de forma gratuita al menos en formato digital.' , tiporespuesta: 'Si - No', subcat_id: '24'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'120'},{nombre:'No',puntaje:'0.0',question_id:'120'}])
question = Question.create([{indicador: 'AC8.4', pregunta: 'Existen programas de difusión científica y/o  transferencia tecnológica donde se realicen colaboraciones con organismos públicos para transferencia de investigación hacia la comunidad, enfocado en sustentabilidad.', tiporespuesta: 'Si - No', subcat_id: '24'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'121'},{nombre:'No',puntaje:'0.0',question_id:'121'}])
question = Question.create([{indicador: 'AC8.5', pregunta: 'Existen programas de difusión científica y/o  transferencia tecnológica enfocada en la sustentabilidad, donde se realice otra actividad no incluida en la lista anterior.', tiporespuesta: 'Si - No', subcat_id: '24'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'122'},{nombre:'No',puntaje:'0.0',question_id:'122'}])

question = Question.create([{indicador: 'GC1.1', pregunta: 'Existe un Reporte de Huella Hídrica para el año evaluado' , tiporespuesta: 'Si - No', subcat_id: '25'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'90.0',question_id:'123'},{nombre:'No',puntaje:'0.0',question_id:'123'}])
question = Question.create([{indicador: 'GC1.2', pregunta: 'El reporte de Huella Hídrica cuenta con una verificación externa', tiporespuesta: 'Si - No', subcat_id: '25'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'124'},{nombre:'No',puntaje:'0.0',question_id:'124'}])

question = Question.create([{indicador: 'GC2.1', pregunta: 'Existe un plan de gestión para el consumo del agua que fije metas de reducción del consumo y defina medidas para lograr dichas metas' , tiporespuesta: 'Si - No', subcat_id: '26'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'125'},{nombre:'No',puntaje:'0.0',question_id:'125'}])
question = Question.create([{indicador: 'GC2.2', pregunta: 'Se ha implementado sistema de captación de agua lluvia en la institución' , tiporespuesta: 'Si - No', subcat_id: '26'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'126'},{nombre:'No',puntaje:'0.0',question_id:'126'}])
question = Question.create([{indicador: 'GC2.3', pregunta: 'Se ha implementado un sistema de tratamiento de aguas grises para reutilización en el campus' , tiporespuesta: 'Si - No', subcat_id: '26'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'127'},{nombre:'No',puntaje:'0.0',question_id:'127'}])
question = Question.create([{indicador: 'GC2.4', pregunta: 'Se ha implementado sistema de urinarios secos' , tiporespuesta: 'Si - No', subcat_id: '26'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'128'},{nombre:'No',puntaje:'0.0',question_id:'128'}])
question = Question.create([{indicador: 'GC2.5', pregunta: 'Se ha implementado un sistema de riego eficiente en sus áreas verdes' , tiporespuesta: 'Si - No', subcat_id: '26'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'129'},{nombre:'No',puntaje:'0.0',question_id:'129'}])
question = Question.create([{indicador: 'GC2.6', pregunta: 'Se ha implementado sistemas de consumo eficiente de agua en griferías (aireadores u otro)' , tiporespuesta: 'Si - No', subcat_id: '26'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'130'},{nombre:'No',puntaje:'0.0',question_id:'130'}])
question = Question.create([{indicador: 'GC2.7', pregunta: 'Se ha implementado sistemas eficientes de uso de agua en estanques de baño (doble descarga u otro)' , tiporespuesta: 'Si - No', subcat_id: '26'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'131'},{nombre:'No',puntaje:'0.0',question_id:'131'}])
question = Question.create([{indicador: 'GC2.8', pregunta: 'Se ha implementado algún otro sistema de uso eficiente del consumo de agua.' , tiporespuesta: 'Si - No', subcat_id: '26'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'132'},{nombre:'No',puntaje:'0.0',question_id:'132'}])
question = Question.create([{indicador: 'GC2.9', pregunta: 'Consumo total de agua (metros cúbicos m3) para el año evaluado' , tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '26'}])


question = Question.create([{indicador: 'GC3.1', pregunta: 'Existe un programa para la preservación y y protección de la biodiversidad nativa en sus áreas verdes' , tiporespuesta: 'Si - No', subcat_id: '27'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'134'},{nombre:'No',puntaje:'0.0',question_id:'134'}])
question = Question.create([{indicador: 'GC3.2', pregunta: 'Se ha realizado un inventario completo de especies en peligro que existan dentro de las instalaciones (flora y fauna)' , tiporespuesta: 'Si - No', subcat_id: '27'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'135'},{nombre:'No',puntaje:'0.0',question_id:'135'}])
question = Question.create([{indicador: 'GC3.3', pregunta: 'Existen planes de protección y mejora de habitats, que incluya recursos y responsables de su ejecución' , tiporespuesta: 'Si - No', subcat_id: '27'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'30.0',question_id:'136'},{nombre:'No',puntaje:'0.0',question_id:'136'}])
question = Question.create([{indicador: 'GC3.4', pregunta: 'Existe algun proyecto educativo que concientice a la comunidad interna sobre las especies presentes en el campus y los cuidados que requieren' , tiporespuesta: 'Si - No', subcat_id: '27'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'137'},{nombre:'No',puntaje:'0.0',question_id:'137'}])
question = Question.create([{indicador: 'GC3.5', pregunta: 'Hay señaléticas y senderos interpretativos que orienten e informen sobre las especies presentes en los campus y las medidas de cuidado implementadas' , tiporespuesta: 'Si - No', subcat_id: '27'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'138'},{nombre:'No',puntaje:'0.0',question_id:'138'}])
question = Question.create([{indicador: 'GC3.6', pregunta: 'Existe algún proyecto de reforestación con flora nativa.' , tiporespuesta: 'Si - No', subcat_id: '27'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'139'},{nombre:'No',puntaje:'0.0',question_id:'139'}])
question = Question.create([{indicador: 'GC3.7', pregunta: 'La institución esta adherida de manera formal a algún programas de cuidado de la biodiversidad nativa local.' , tiporespuesta: 'Si - No', subcat_id: '27'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'140'},{nombre:'No',puntaje:'0.0',question_id:'140'}])
question = Question.create([{indicador: 'GC3.8', pregunta: 'Otra acción que no este en la lista anterior que cumple el objetivo del indicador' , tiporespuesta: 'Si - No', subcat_id: '27'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'141'},{nombre:'No',puntaje:'0.0',question_id:'141'}])


question = Question.create([{indicador: 'GC4.1', pregunta: 'La institución cuenta con una política de manejo sustentable de sus áreas verdes' , tiporespuesta: 'Si - No', subcat_id: '28'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'142'},{nombre:'No',puntaje:'0.0',question_id:'142'}])
question = Question.create([{indicador: 'GC4.2', pregunta: 'Se ha Implementado un sistema de riego eficiente y tecnificado.' , tiporespuesta: 'Si - No', subcat_id: '28'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'15.0',question_id:'143'},{nombre:'No',puntaje:'0.0',question_id:'143'}])
question = Question.create([{indicador: 'GC4.3', pregunta: 'Se utiliza especies adecuadas para zona climática y/o de bajo consumo hídrico.' , tiporespuesta: 'Si - No', subcat_id: '28'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'15.0',question_id:'144'},{nombre:'No',puntaje:'0.0',question_id:'144'}])
question = Question.create([{indicador: 'GC4.4', pregunta: 'Se realiza control de especies alergénicas, para reducir incidencia de alergias en la comunidad' , tiporespuesta: 'Si - No', subcat_id: '28'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'15.0',question_id:'145'},{nombre:'No',puntaje:'0.0',question_id:'145'}])
question = Question.create([{indicador: 'GC4.5', pregunta: 'Se realiza una gestión integrada de fertilización, dando preferencia a uso de fertilizantes orgánicos' , tiporespuesta: 'Si - No', subcat_id: '28'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'15.0',question_id:'146'},{nombre:'No',puntaje:'0.0',question_id:'146'}])
question = Question.create([{indicador: 'GC4.6', pregunta: 'Se realiza una gestión integrada de pestes, minimizando o eliminando uso de biocidas sintéticos' , tiporespuesta: 'Si - No', subcat_id: '28'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'15.0',question_id:'147'},{nombre:'No',puntaje:'0.0',question_id:'147'}])
question = Question.create([{indicador: 'GC4.7', pregunta: 'Gestión integral de residuos vegetales, dentro de las instalaciones de la institución o con apoyo de un tercero que certifique la revaloración de los residuos. (Ej: Compostaje, lombricultura)' , tiporespuesta: 'Si - No', subcat_id: '28'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'15.0',question_id:'148'},{nombre:'No',puntaje:'0.0',question_id:'148'}])
question = Question.create([{indicador: 'GC4.8', pregunta: 'Metros cuadrados de áreas verdes que operan bajo la poítica' , tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '28'}])


question = Question.create([{indicador: 'GC5.1', pregunta: 'La institución tiene una política de servicios alimentación sustentable ' , tiporespuesta: 'Si - No', subcat_id: '29'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'150'},{nombre:'No',puntaje:'0.0',question_id:'150'}])
question = Question.create([{indicador: 'GC5.2', pregunta: 'Existen menús vegetarianos disponibles para todos (Ej: En todos los campus)' , tiporespuesta: 'Si - No', subcat_id: '29'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'15.0',question_id:'151'},{nombre:'No',puntaje:'0.0',question_id:'151'}])
question = Question.create([{indicador: 'GC5.3', pregunta: 'Existe un listado público de proveedores locales para fomentar la economía local' , tiporespuesta: 'Si - No', subcat_id: '29'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'15.0',question_id:'152'},{nombre:'No',puntaje:'0.0',question_id:'152'}])
question = Question.create([{indicador: 'GC5.4', pregunta: 'Se utilizan alimentos provenientes de huertas comunitarias de la institución, a través de almuerzos colaborativos u otras instancias similares' , tiporespuesta: 'Si - No', subcat_id: '29'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'15.0',question_id:'153'},{nombre:'No',puntaje:'0.0',question_id:'153'}])
question = Question.create([{indicador: 'GC5.5', pregunta: 'Se desarrollan campañas periódicas sobre el impacto social y ambiental de distintas alternativas de alimentación' , tiporespuesta: 'Si - No', subcat_id: '29'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'15.0',question_id:'154'},{nombre:'No',puntaje:'0.0',question_id:'154'}])
question = Question.create([{indicador: 'GC5.6', pregunta: 'Se desarrollan programas de alimentación saludable' , tiporespuesta: 'Si - No', subcat_id: '29'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'15.0',question_id:'155'},{nombre:'No',puntaje:'0.0',question_id:'155'}])
question = Question.create([{indicador: 'GC5.7', pregunta: 'Existen programas para la reducción del desperdicio de comida' , tiporespuesta: 'Si - No', subcat_id: '29'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'15.0',question_id:'156'},{nombre:'No',puntaje:'0.0',question_id:'156'}])
question = Question.create([{indicador: 'GC5.8', pregunta: 'Se ha prohibido el uso de utensilios desechables' , tiporespuesta: 'Si - No', subcat_id: '29'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'15.0',question_id:'157'},{nombre:'No',puntaje:'0.0',question_id:'157'}])
question = Question.create([{indicador: 'GC5.9', pregunta: 'Se utiliza loza definitiva en los casinos, reduciendo la generación de residuos' , tiporespuesta: 'Si - No', subcat_id: '29'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'15.0',question_id:'158'},{nombre:'No',puntaje:'0.0',question_id:'158'}])
question = Question.create([{indicador: 'GC5.10', pregunta: 'Existe un programa para el aprovechamiento de residuos orgánicos generados en casinos' , tiporespuesta: 'Si - No', subcat_id: '29'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'15.0',question_id:'159'},{nombre:'No',puntaje:'0.0',question_id:'159'}])


question = Question.create([{indicador: 'GC6.1', pregunta: 'Se la elaborado una política  para la compra y contratación de productos y servicios sustentables, que considere a lo menos: compra de aparatos electrónicos, productos de limpieza y papel' , tiporespuesta: 'Si - No', subcat_id: '30'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'1.0',question_id:'160'},{nombre:'No',puntaje:'0.0',question_id:'160'}])
question = Question.create([{indicador: 'GC6.2', pregunta: 'Se ha desarrollado una guía de preveedores y servicios que cumplan con criterios de sustentabilidad, disponible para todo el personal.' , tiporespuesta: 'Si - No', subcat_id: '30'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'161'},{nombre:'No',puntaje:'0.0',question_id:'161'}])
question = Question.create([{indicador: 'GC6.3', pregunta: 'Se ha desarrollado un diagnóstico del impacto ambiental y social de las compras y servicios contratados por la institución.' , tiporespuesta: 'Si - No', subcat_id: '30'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'162'},{nombre:'No',puntaje:'0.0',question_id:'162'}])
question = Question.create([{indicador: 'GC6.4', pregunta: 'Se han incluído dentro de las licitaciones de servicios criterios de sustentabilidad.' , tiporespuesta: 'Si - No', subcat_id: '30'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'163'},{nombre:'No',puntaje:'0.0',question_id:'163'}])
question = Question.create([{indicador: 'GC6.5', pregunta: 'Se ha establecido un protocolo mandatorio y un sistema de seguimiento de compras que contempla criterios de sustentabilidad' , tiporespuesta: 'Si - No', subcat_id: '30'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'40.0',question_id:'164'},{nombre:'No',puntaje:'0.0',question_id:'164'}])
question = Question.create([{indicador: 'GC6.6', pregunta: 'Ha firmado acuerdos de colaboración con otras instituciones para establecer criterios de compra comunes, y así amplificar el impacto en proveedores' , tiporespuesta: 'Si - No', subcat_id: '30'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'50.0',question_id:'165'},{nombre:'No',puntaje:'0.0',question_id:'165'}])


question = Question.create([{indicador: 'GC7.1', pregunta: 'Metros cuadrados construidos (o remodelados) durante los últimos 5 años, que cuenten con máximo nivel de certificación de sustentabilidad  (Certificación sobresaliente según CES)' , tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '31'}])
question = Question.create([{indicador: 'GC7.2', pregunta: 'Metros cuadrados construidos (o remodelados) durante los últimos 5 años, que cuenten con certificación de sustentabilidad nivel intermedio (Certificación destacada según CES)' , tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '31'}])
question = Question.create([{indicador: 'GC7.3', pregunta: 'Metros cuadrados construidos (o remodelados) durante los últimos 5 años, que cuenten con certificación de sustentabilidad nivel mínimo (Edificio certificado según CES)' , tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '31'}])


question = Question.create([{indicador: 'GC8.1', pregunta: 'Metros cuadrados construídos que cuentan con certificación de operación sustentable (LEED, CES, protocolo interno)' , tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '32'}])
question = Question.create([{indicador: 'GC8.2', pregunta: 'Metros cuadrados construídos de edificios operando bajo protocolo de operación sustentable interno' , tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '32'}])
question = Question.create([{indicador: 'GC8.3', pregunta: 'En el protocolo interno se incluye el manejo eficiente de energía' , tiporespuesta: 'Si - No', subcat_id: '32'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'171'},{nombre:'No',puntaje:'0.0',question_id:'171'}])
question = Question.create([{indicador: 'GC8.4', pregunta: 'En el protocolo interno se incluye el manejo eficiente del agua' , tiporespuesta: 'Si - No', subcat_id: '32'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'172'},{nombre:'No',puntaje:'0.0',question_id:'172'}])
question = Question.create([{indicador: 'GC8.5', pregunta: 'En el protocolo interno se incluye calidad del aire interior' , tiporespuesta: 'Si - No', subcat_id: '32'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'173'},{nombre:'No',puntaje:'0.0',question_id:'173'}])
question = Question.create([{indicador: 'GC8.6', pregunta: 'En el protocolo interno se incluye una política de limpieza amigable con el medio ambiente' , tiporespuesta: 'Si - No', subcat_id: '32'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'174'},{nombre:'No',puntaje:'0.0',question_id:'174'}])
question = Question.create([{indicador: 'GC8.7', pregunta: 'En el protocolo interno se incluye la gestión integral de residuos' , tiporespuesta: 'Si - No', subcat_id: '32'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'175'},{nombre:'No',puntaje:'0.0',question_id:'175'}])


question = Question.create([{indicador: 'GC9.1', pregunta: 'Existe un plan de gestión para el consumo de la energía que fije metas de reducción y defina medidas concretas para reducir el consumo' , tiporespuesta: 'Si - No', subcat_id: '33'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'176'},{nombre:'No',puntaje:'0.0',question_id:'176'}])
question = Question.create([{indicador: 'GC9.2', pregunta: 'Reemplazo de luminarias por alternativas eficientes (ej: LED)' , tiporespuesta: 'Si - No', subcat_id: '33'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'177'},{nombre:'No',puntaje:'0.0',question_id:'177'}])
question = Question.create([{indicador: 'GC9.3', pregunta: 'Reducción de luminarias en sectores donde era ineficiente su uso' , tiporespuesta: 'Si - No', subcat_id: '33'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'178'},{nombre:'No',puntaje:'0.0',question_id:'178'}])
question = Question.create([{indicador: 'GC9.4', pregunta: 'Utilización de aparatos electrónicos de bajo consumo' , tiporespuesta: 'Si - No', subcat_id: '33'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'179'},{nombre:'No',puntaje:'0.0',question_id:'179'}])
question = Question.create([{indicador: 'GC9.5', pregunta: 'Campañas de uso eficiente de la energía' , tiporespuesta: 'Si - No', subcat_id: '33'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'180'},{nombre:'No',puntaje:'0.0',question_id:'180'}])
question = Question.create([{indicador: 'GC9.6', pregunta: 'Sistemas de climatización eficientes' , tiporespuesta: 'Si - No', subcat_id: '33'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'181'},{nombre:'No',puntaje:'0.0',question_id:'181'}])
question = Question.create([{indicador: 'GC9.7', pregunta: 'Monitoreo en tiempo real de la energía' , tiporespuesta: 'Si - No', subcat_id: '33'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'182'},{nombre:'No',puntaje:'0.0',question_id:'182'}])
question = Question.create([{indicador: 'GC9.8', pregunta: 'Mantener un registro del consumo energético actualizado  de forma semestral disponible a consulta de la comunidad' , tiporespuesta: 'Si - No', subcat_id: '33'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'183'},{nombre:'No',puntaje:'0.0',question_id:'183'}])
question = Question.create([{indicador: 'GC9.9', pregunta: 'Consumo total de energía (Mwh) para el año evaluado' , tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '33'}])

question = Question.create([{indicador: 'GC10.1', pregunta: 'MWH generados con la ERNC para el año evaluado' , tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '34'}])


question = Question.create([{indicador: 'GC13.1', pregunta: 'Se han elaborado protocolos o estrategias de disposición segura de residuos peligrosos como electrónicos y químicos' , tiporespuesta: 'Si - No', subcat_id: '37'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'50.0',question_id:'186'},{nombre:'No',puntaje:'0.0',question_id:'186'}])
question = Question.create([{indicador: 'GC13.2', pregunta: 'La institución participa de  algún programa de reciclaje o reutilización de residuos electrónicos.' , tiporespuesta: 'Si - No', subcat_id: '37'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'50.0',question_id:'187'},{nombre:'No',puntaje:'0.0',question_id:'187'}])


question = Question.create([{indicador: 'GC14.1', pregunta: 'La institución ha realizado una medición de la partición modal de los medios de transporte de su comunidad (medios en los que se trasladan  a la institución los estudiantes y trabajadores) ' , tiporespuesta: 'Si - No', subcat_id: '38'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'188'},{nombre:'No',puntaje:'0.0',question_id:'188'}])
question = Question.create([{indicador: 'GC14.2', pregunta: 'Total de viajes realizados en vehículo con un pasajero para el año evaluado' , tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '38'}])
question = Question.create([{indicador: 'GC14.1', pregunta: 'Total de viajes realizados por su comunidad para el año evaluado (Incluye: Medios no motorizados, transporte público, automóvil)' , tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '38'}])


question = Question.create([{indicador: 'GC15.1', pregunta: 'Se ha elaborado un plan con acciones concretas para aumentar el traslado de su comunidad en medios de transporte más sustentable' , tiporespuesta: 'Si - No', subcat_id: '39'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'191'},{nombre:'No',puntaje:'0.0',question_id:'191'}])
question = Question.create([{indicador: 'GC15.2', pregunta: 'Existen estacionamientos de bicicleta en todos sus campus' , tiporespuesta: 'Si - No', subcat_id: '39'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'192'},{nombre:'No',puntaje:'0.0',question_id:'192'}])
question = Question.create([{indicador: 'GC15.3', pregunta: 'Se han realizado campañas para desincentivar el uso de automovil particular' , tiporespuesta: 'Si - No', subcat_id: '39'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'193'},{nombre:'No',puntaje:'0.0',question_id:'193'}])
question = Question.create([{indicador: 'GC15.4', pregunta: 'Existen programas de incentivo de uso de bicicleta' , tiporespuesta: 'Si - No', subcat_id: '39'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'10.0',question_id:'194'},{nombre:'No',puntaje:'0.0',question_id:'194'}])
question = Question.create([{indicador: 'GC15.5', pregunta: 'Existe programa de auto compartido o carpooling' , tiporespuesta: 'Si - No', subcat_id: '39'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'195'},{nombre:'No',puntaje:'0.0',question_id:'195'}])
question = Question.create([{indicador: 'GC15.6', pregunta: 'La institución cuenta con buses de acercamiento' , tiporespuesta: 'Si - No', subcat_id: '39'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'196'},{nombre:'No',puntaje:'0.0',question_id:'196'}])
question = Question.create([{indicador: 'GC15.7', pregunta: 'Se ha realizado la reducción de estacionamientos de autos' , tiporespuesta: 'Si - No', subcat_id: '39'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'197'},{nombre:'No',puntaje:'0.0',question_id:'197'}])


question = Question.create([{indicador: 'RS1.1', pregunta: 'Existen programas de apoyo para facilitar el acceso de estudiantes provenientes de situaciones socioeconomicas desfavorables.' , tiporespuesta: 'Si - No', subcat_id: '40'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'40.0',question_id:'198'},{nombre:'No',puntaje:'0.0',question_id:'198'}])
question = Question.create([{indicador: 'RS1.2', pregunta: 'Número de estudiantes inscritos en el año evaluado provienentes de los 6 primeros deciles' , tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '40'}])

question = Question.create([{indicador: 'RS4.1', pregunta: 'Existe una colaboración activa orientada a la sustentabilidad con una organización privada' , tiporespuesta: 'Si - No', subcat_id: '43'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'200'},{nombre:'No',puntaje:'0.0',question_id:'200'}])
question = Question.create([{indicador: 'RS4.2', pregunta: 'Existe una colaboración activa orientada a la sustentabilidad con una entidad del estado' , tiporespuesta: 'Si - No', subcat_id: '43'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'201'},{nombre:'No',puntaje:'0.0',question_id:'201'}])
question = Question.create([{indicador: 'RS4.3', pregunta: 'Existe una colaboración activa orientada a la sustentabilidad con una institución de educación superior' , tiporespuesta: 'Si - No', subcat_id: '43'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'202'},{nombre:'No',puntaje:'0.0',question_id:'202'}])
question = Question.create([{indicador: 'RS4.4', pregunta: 'Existe una colaboración activa orientada a la sustentabilidad con una ONG' , tiporespuesta: 'Si - No', subcat_id: '43'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'203'},{nombre:'No',puntaje:'0.0',question_id:'203'}])
question = Question.create([{indicador: 'RS4.5', pregunta: 'Existe una vinculación permanente con alguna de estas instituciones en proyectos de sustentabilidad' , tiporespuesta: 'Si - No', subcat_id: '43'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'40.0',question_id:'204'},{nombre:'No',puntaje:'0.0',question_id:'204'}])


question = Question.create([{indicador: 'RS5.1', pregunta: 'Existe un órgano o unidad que gestione la participación de la institución en políticas públicas' , tiporespuesta: 'Si - No', subcat_id: '44'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'205'},{nombre:'No',puntaje:'0.0',question_id:'205'}])
question = Question.create([{indicador: 'RS5.2', pregunta: 'Existe un diagnóstico de las participaciones en materia de sustentabilidad en las que se ha involucrado la institución durante el año evaluado' , tiporespuesta: 'Si - No', subcat_id: '44'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'40.0',question_id:'206'},{nombre:'No',puntaje:'0.0',question_id:'206'}])
question = Question.create([{indicador: 'RS5.3', pregunta: 'La institución ha participado en la elaboración de una política regional o nacional en el año evaluado' , tiporespuesta: 'Si - No', subcat_id: '44'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'40.0',question_id:'207'},{nombre:'No',puntaje:'0.0',question_id:'207'}])


question = Question.create([{indicador: 'RS6.1', pregunta: 'Existe una política de relacionamiento comunitario con las comunidades aledañas a los territorios donde están insertas las instalaciones de la institución' , tiporespuesta: 'Si - No', subcat_id: '45'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'35.0',question_id:'208'},{nombre:'No',puntaje:'0.0',question_id:'208'}])
question = Question.create([{indicador: 'RS6.2', pregunta: 'Existe una unidad o encargado dedicado a coordinar las relaciones y comunicación permanente con las comunidades aledañas a los territorios donde están insertas las instalaciones de la institución' , tiporespuesta: 'Si - No', subcat_id: '45'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'35.0',question_id:'209'},{nombre:'No',puntaje:'0.0',question_id:'209'}])
question = Question.create([{indicador: 'RS6.3', pregunta: 'Existe al menos un proyecto activo que vincule permanentemente a la Institución con las comunidades vecinas' , tiporespuesta: 'Si - No', subcat_id: '45'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'30.0',question_id:'210'},{nombre:'No',puntaje:'0.0',question_id:'210'}])


question = Question.create([{indicador: 'RS8.1', pregunta: 'Se aplica una encuesta para medir el indice de satisfacción laboral de los trabajadores en la institución' , tiporespuesta: 'Si - No', subcat_id: '47'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'20.0',question_id:'211'},{nombre:'No',puntaje:'0.0',question_id:'211'}])
question = Question.create([{indicador: 'RS8.2', pregunta: 'Porcentaje de trabajadores que tienen un alto ìndice de satisfacción laboral según consulta aplicada (sobre 60% de satisfacción, según escala de la encuesta)' , tiporespuesta: 'Alternativa', subcat_id: '47'}])
alternativa = Alternativa.create([{nombre:'5%',puntaje:'0.05',question_id:'212'},{nombre:'10%',puntaje:'0.10',question_id:'212'},{nombre:'15%',puntaje:'0.15',question_id:'212'},{nombre:'20%',puntaje:'0.20',question_id:'212'},
{nombre:'25%',puntaje:'0.25',question_id:'212'},{nombre:'30%',puntaje:'0.30',question_id:'212'},{nombre:'35%',puntaje:'0.35',question_id:'212'},{nombre:'40%',puntaje:'0.40',question_id:'212'},{nombre:'45%',puntaje:'0.45',question_id:'212'},
{nombre:'50%',puntaje:'0.50',question_id:'212'},{nombre:'55%',puntaje:'0.55',question_id:'212'},{nombre:'60%',puntaje:'0.60',question_id:'212'},{nombre:'65%',puntaje:'0.65',question_id:'212'},{nombre:'70%',puntaje:'0.70',question_id:'212'},
{nombre:'75%',puntaje:'0.75',question_id:'212'},{nombre:'80%',puntaje:'0.80',question_id:'212'},{nombre:'85%',puntaje:'0.85',question_id:'212'},{nombre:'90%',puntaje:'0.90',question_id:'212'},{nombre:'95%',puntaje:'0.95',question_id:'212'},
{nombre:'100%',puntaje:'1.00',question_id:'212'}])
question = Question.create([{indicador: 'RS8.3', pregunta: 'La institución ha implementado un programa de bienestar para los empleados durante el año evaluado' , tiporespuesta: 'Si - No', subcat_id: '47'}])
alternativa = Alternativa.create([{nombre:'Si',puntaje:'30.0',question_id:'213'},{nombre:'No',puntaje:'0.0',question_id:'213'}])


question = Question.create([{indicador: 'RS9.1', pregunta: 'Número de trabajadores adheridos a un sindicato o asociaciones (en el caso de instituciones públicas)' , tiporespuesta: 'Ingresa Valor Manualmente', subcat_id: '48'}])
