class CreateHistoria < ActiveRecord::Migration[5.1]
  def change
    create_table :historia do |t|
      t.float :global
      t.float :gobpon
      t.float :gobbru
      t.float :gob1pon
      t.float :gob1bru
      t.float :gob2pon
      t.float :gob2bru
      t.float :gob3pon
      t.float :gob3bru
      t.float :gob4pon
      t.float :gob4bru
      t.float :gob5pon
      t.float :gob5bru
      t.float :gob6pon
      t.float :gob6bru
      t.float :cupon
      t.float :cubru
      t.float :cu1pon
      t.float :cu1bru
      t.float :cu2pon
      t.float :cu2bru
      t.float :cu3pon
      t.float :cu3bru
      t.float :cu4pon
      t.float :cu4bru
      t.float :cu5pon
      t.float :cu5bru
      t.float :cu6pon
      t.float :cu6bru
      t.float :cu7pon
      t.float :cu7bru
      t.float :acpon
      t.float :acbru
      t.float :ac1pon
      t.float :ac1bru
      t.float :ac2pon
      t.float :ac2bru
      t.float :ac3pon
      t.float :ac3bru
      t.float :ac4pon
      t.float :ac4bru
      t.float :ac5pon
      t.float :ac5bru
      t.float :ac6pon
      t.float :ac6bru
      t.float :ac7pon
      t.float :ac7bru
      t.float :ac8pon
      t.float :ac8bru
      t.float :gcpon
      t.float :gcbru
      t.float :gc1pon
      t.float :gc1bru
      t.float :gc2pon
      t.float :gc2bru
      t.float :gc3pon
      t.float :gc3bru
      t.float :gc4pon
      t.float :gc4bru
      t.float :gc5pon
      t.float :gc5bru
      t.float :gc6pon
      t.float :gc6bru
      t.float :gc7pon
      t.float :gc7bru
      t.float :gc8pon
      t.float :gc8bru
      t.float :gc9pon
      t.float :gc9bru
      t.float :gc10pon
      t.float :gc10bru
      t.float :gc11pon
      t.float :gc11bru
      t.float :gc12pon
      t.float :gc12bru
      t.float :gc13pon
      t.float :gc13bru
      t.float :gc14pon
      t.float :gc14bru
      t.float :gc15pon
      t.float :gc15bru
      t.float :rspon
      t.float :rsbru
      t.float :rs1pon
      t.float :rs1bru
      t.float :rs2pon
      t.float :rs2bru
      t.float :rs3pon
      t.float :rs3bru
      t.float :rs4pon
      t.float :rs4bru
      t.float :rs5pon
      t.float :rs5bru
      t.float :rs6pon
      t.float :rs6bru
      t.float :rs7pon
      t.float :rs7bru
      t.float :rs8pon
      t.float :rs8bru
      t.float :rs9pon
      t.float :rs9bru

      t.timestamps
    end
  end
end
